export { RegisterPag } from './RegisterPage'
export FormikBasicPage from '../03-forms/pages/formikBasicPage'
export FormikYupPage from '../03-forms/pages/FormikYupPage'
export FormikComponents from '../03-forms/pages/FormikComponents'
export FormikAbstraction from '../03-forms/pages/FormikAbstraction'